import type { NextPage } from 'next'
import Head from 'next/head'
import ProjectsController from '../../components/ProjectsController'
import { loader } from '../../data/projects/_index'
import styles from '../../styles/pages/Projects.module.scss'

const Projects: NextPage = () => {
  const project = loader('euris-gucci-projects');
  return (
    <div className={styles.container}>
      <Head>
        <title>Diego Esteves – portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        {project ? <ProjectsController initialProject={project.excerpt} /> : null}
      </main>
    </div>
  )
}

export default Projects
