import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/pages/About.module.scss'

const About: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Diego Esteves – portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        about
      </main>
    </div>
  )
}

export default About
