import type { NextPage } from 'next'
import Head from 'next/head'
import AboutMe from '../components/AboutMe';
import BigBanner from '../components/BigBanner';
import styles from '../styles/pages/Home.module.scss'
import { useState } from 'react';
import { ProjectExerpt } from '../types/Project';
import ProjectsController from '../components/ProjectsController';

const Home: NextPage = () => {  
  const [activeProject, setActiveProject] = useState<ProjectExerpt|null>(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Diego Esteves – portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        {!activeProject ? (
          <>
            <BigBanner />
            <AboutMe />
          </>
        ) : null}
        <ProjectsController activeProjectChanged={(excerpt) => setActiveProject(excerpt)}></ProjectsController>
      </main>
    </div>
  )
}

export default Home
