import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/pages/Home.module.scss'

export interface HomeData {
  name: string;
} 

const Home: NextPage<HomeData> = ({ name }) => {      
  return (
    <div className={styles.container}>
      <Head>
        <title>Diego Esteves – portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        Hello, {name} :)
        <br />
        Home
      </main>
    </div>
  )
}

export const getStaticProps: HomeData = () => {
  return {
    props: {
      name: "diego"
    }
  }
}

export default Home
